version: '2'
services:
    kafkalens-app:
        image: kafkalens
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://kafkalens-mysql:3306/kafkalens?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=kafkalens-elasticsearch:9300
        ports:
            - 8080:8080
    kafkalens-mysql:
        extends:
            file: mysql.yml
            service: kafkalens-mysql
    kafkalens-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: kafkalens-elasticsearch
